version: "3"
   
services:
  db:
    container_name: postgres-db
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  webapp:
    container_name: newsapp
    build: ./newsapp
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./newsapp:/webapp
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: