# Generated by Django 4.0.3 on 2022-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, upload_to='news_images'),
        ),
    ]
