# Generated by Django 4.0.3 on 2022-03-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='news_images', verbose_name='Image')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
