# Generated by Django 4.0.3 on 2022-03-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_news_images_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, upload_to='news_images'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
